### ISSUE TITLE
Dependencies installed, but main.py throws errors

### ISSUE THREAD

**Issue by Kabouik** [matcool/term-tris#2]
I installed `asciimatics` and `keyboard` using `pip`, ncurses is installed, but I can't run `main.py` regardless of the version of Python I use:

```
nemo@Sailfish nnn]$ devel-su pip install asciimatics
Password: 
Collecting asciimatics
  Downloading asciimatics-1.11.0-py2.py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 1.4 MB/s 
Requirement already satisfied: future in /usr/lib/python3.8/site-packages (from asciimatics) (0.18.2)
Requirement already satisfied: Pillow>=2.7.0 in /usr/lib/python3.8/site-packages (from asciimatics) (5.4.1)
Collecting pyfiglet>=0.7.2
  Downloading pyfiglet-0.8.post1-py2.py3-none-any.whl (865 kB)
     |████████████████████████████████| 865 kB 2.9 MB/s 
Collecting wcwidth
  Downloading wcwidth-0.1.9-py2.py3-none-any.whl (19 kB)
Installing collected packages: pyfiglet, wcwidth, asciimatics
Successfully installed asciimatics-1.11.0 pyfiglet-0.8.post1 wcwidth-0.1.9
[nemo@Sailfish nnn]$ devel-su pip install keyboard   
Password: 
Collecting keyboard
  Downloading keyboard-0.13.5-py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 828 kB/s 
Installing collected packages: keyboard
Successfully installed keyboard-0.13.5
```

```
[nemo@Sailfish term-tris]$ python main.py 
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from asciimatics.screen import Screen
ImportError: No module named asciimatics.screen
[nemo@Sailfish term-tris]$ 
```

```
[nemo@Sailfish term-tris]$ python3 main.py 
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from asciimatics.screen import Screen
  File "/usr/lib/python3.8/site-packages/asciimatics/screen.py", line 2152, in <module>
    import curses
  File "/usr/lib/python3.8/curses/__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
[nemo@Sailfish term-tris]$ 
```
I tried as root, but got the same errors. Any ideas? Is it possible my version of ncurses is too old? I only have 6.1 available.

**Comment by jquast** [comment]
However your python was installed, by package or manually, It did not include or link with ncurses.

If you manually compile python, the configure script makes a report of modules that will not be built because `ncurses/curses.h` was not found, or perhaps, by manually compiling it, it will be found.

best wishes

**Comment by Kabouik** [comment]
Thanks for your answer. You are absolutely right, the repository version of `python3` I initially had was built without `ncurses`, and this led to other applications failing to run, like `glances` for instance. However, I later found a community version which fixes that dependency and I could confirm that `glances` would then correctly run, but I am still getting the same issue in `term-tris` so I am not sure why it is not picking the updated python version like `glances` did.

**Comment by jquast** [comment]
You have more than one version of python installed, and term-tris was installed through the bad one. Try using the “which” command to locate the bad one,

which python
which pip
devel-su which python
devel-su which pip
which term-tris
which glances

Etc. when you find the location of the bad python interpreter, you can call into the pip module to uninstall term-this from it, and use the good python interpreter to install term-tris

/usr/local/bad/python -m pip uninstall term-tris


/usr/local/good/python -m pip install term-tris

**Comment by Kabouik** [comment]
Oh, maybe that is where the issue is then. I didn't install `term-tris`, I just cloned the repository and was trying to run `python3 main.py` after installing `asciimatics` and `keyboard` using `pip`.

I did try installing `term-tris` using `pip` before, but no matching version was found, which is why I tried cloning and running the executable. Perhaps there is no version compatible with arm devices?

**Comment by jquast** [comment]
You are right that term-tris is not on pypi, it is missing setup.py, too, so, the way you are running is fine.

but it should work fine on arm cpu as far as I can tell, anyway I’ve reached the end of my support contract lol, best wishes and good luck, “Tetris 99” is free on Nintendo switch with a Nintendo online account, I highly suggest that one, lol!
